#!/usr/bin/env bash
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "master" ]; then
  echo 'Direct commits to master are blocked. Please create a feature branch and open a PR.'
  exit 1
fi
exit 0